# Generated by Django 4.1.5 on 2023-01-22 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_content_post_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content_tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_content', models.CharField(max_length=25)),
                ('tag_click', models.IntegerField()),
                ('tag_used', models.IntegerField()),
            ],
        ),
    ]
