# Generated by Django 4.1.5 on 2023-01-22 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_contents'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField(max_length=150)),
                ('id_commenter', models.IntegerField()),
                ('id_contentCreator', models.IntegerField()),
                ('number_content', models.IntegerField()),
            ],
        ),
    ]
