# Generated by Django 4.1.5 on 2023-01-22 15:48

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_coments'),
    ]

    operations = [
        migrations.AddField(
            model_name='contents',
            name='coments',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None), default=(1, 2), size=None),
            preserve_default=False,
        ),
    ]
