# Generated by Django 4.1.5 on 2023-01-23 02:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_user_additions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contents',
            name='coments',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(null=True), size=None),
        ),
    ]
