# Generated by Django 4.1.5 on 2023-01-23 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_contents_coments'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_additions',
            name='content_count',
            field=models.IntegerField(default=0),
        ),
    ]
