# Generated by Django 4.1.5 on 2023-01-23 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_user_additions_content_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_additions',
            name='id_user',
            field=models.IntegerField(default=0),
        ),
    ]
