# Generated by Django 4.1.5 on 2023-01-27 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20230127_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='contents',
            name='image',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
